#############
# Dockerfile to render objects in Blender
#Based on Ubuntu
#############
#Download image of Ubuntu 
FROM ubuntu
LABEL authors="Egor Budlov <budlow@yandex.ru>"
#Update
RUN apt-get update
#Install all necessary packages
RUN apt-get install sudo
RUN sudo apt install -y software-properties-common
RUN sudo add-apt-repository ppa:thomas-schiex/blender 
RUN apt-get update
RUN sudo apt-get install -y blender
RUN sudo apt-get install -y git
RUN apt-get install -y dos2unix
RUN sudo pip3 install scikit-image
RUN sudo pip3 install opencv-python
RUN mkdir /bscript \
	git clone https://github.com/8-lines/blender_PBR
#Set working directory
WORKDIR /bscript/blender_PBR
RUN dos2unix /docker-container/linux-run.sh
CMD /docker-container/run-linux.sh